modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0 license http://www.apache.org/licenses/LICENSE-2.0"

[[mods]]
modId="bedrockite"
version="1.5.0-beta"
displayName="Bedrockite"
displayURL="https://github.com/Miki85cz/BedrockiteMod"
authors="§a§lMiki85cz"

description='''
§rThis mod adds a new material §bBedrockite §rthat you can use to make the §bBedrockite pickaxe §rwhich is able to mine bedrock. It is hard to obtain and in survival you can only get cracked bedrock (which can be mined with anything)

§6If you find any issue please report it! https://github.com/Miki85cz/BedrockiteMod/issues
'''

logoFile="logo.png"

[[mixins]]
config="bedrockite.mixins.json"

[[dependencies.bedrockite]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bedrockite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21, 1.21.2)"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration