modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0 license http://www.apache.org/licenses/LICENSE-2.0"

[[mods]]
modId="bedrockite"
version="1.4.8-beta"
displayName="Bedrockite"
displayURL=""
credits=""
authors="Miki85cz"

description='''
This mod adds a new material Bedrockite that you can use to make the Bedrockite pickaxe which is able to mine bedrock. It is hard to obtain and in survival you can only get cracked bedrock (which can be mined with anything)
'''

[[mixins]]
config="bedrockite.mixins.json"

[[dependencies.bedrockite]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bedrockite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21, 1.21.2)"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration